- hosts: all
  become: yes
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: copy war file to the remote server
      copy:
        src: /var/lib/jenkins/workspace/app-demo/target/simple-app*.war
        dest: /tomcat/webapps/simple-app.war
    
