- hosts: hosts
  become: yes
  become_user: root
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: copy war file to the remote server
      copy:
        src: /var/lib/jenkins/workspace/simple-app/target/simple-app-3.0.0-SNAPSHOT.war
        dest: /tomcat/webapps/simple-app.war
    
