- hosts: all
  become: yes
  tasks:
    - name: copy war file to the remote server
      copy:
        src: /var/lib/jenkins/workspace/simple-app/target/simple-app*.war
        dest: /tomcat/webapps/simple-app.war
    
